# Generated by Django 6.0.2 on 2026-02-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/'),
        ),
    ]
