# Generated by Django 5.2.4 on 2026-02-27 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='영상 제목')),
                ('video', models.FileField(upload_to='course/videos/%Y/%m/%d/', verbose_name='영상 파일')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
