# Generated by Django 6.0.2 on 2026-02-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_students_course_teacher'),
        ('course', '0002_course_video'),
    ]

    operations = [
    ]
