# Generated by Django 6.0.2 on 2026-02-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_price'),
        ('course', '0003_merge_20260220_1529'),
    ]

    operations = [
    ]
