# Generated by Django 6.0.2 on 2026-02-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_merge_20260220_1521'),
        ('course', '0004_merge_20260220_1550'),
    ]

    operations = [
    ]
