# Generated by Django 6.0.2 on 2026-02-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_merge_20260220_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('korean', '국어'), ('math', '수학'), ('english', '영어'), ('social', '사회'), ('science', '과학'), ('etc', '기타')], default='etc', max_length=20),
        ),
    ]
