# Generated by Django 6.0.2 on 2026-02-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_thumbnail'),
        ('course', '0005_merge_20260220_1622'),
    ]

    operations = [
    ]
