# Generated by Django 6.0.2 on 2026-02-23 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
    ]
