# Generated by Django 6.0.2 on 2026-02-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_merge_0004_course_thumbnail_0005_merge_20260220_1622'),
        ('course', '0007_alter_course_options'),
    ]

    operations = [
    ]
