# Generated by Django 5.2.4 on 2026-02-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('student', '학생'), ('teacher', '선생님')], max_length=10, null=True, verbose_name='가입 유형'),
        ),
    ]
