# Generated by Django 5.2.4 on 2026-02-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_customuser_id_alter_passwordhistory_id_and_more'),
        ('common', '0002_alter_customuser_role'),
    ]

    operations = [
    ]
