# Generated by Django 6.0.2 on 2026-02-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_customuser_role_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='자기소개'),
        ),
    ]
