# Generated by Django 6.0.2 on 2026-02-26 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_customuser_id_alter_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_password_change',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='마지막 비밀번호 변경일'),
            preserve_default=False,
        ),
    ]
