"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--pt8=vv_#v9!hyd4+%=%nq44jjzi6+97-8l0*0a##q($$xgi4_"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'Board.apps.BoardConfig',
    'Main.apps.MainConfig',
    'common.apps.CommonConfig',
    'course.apps.CourseConfig',
    'StudentPage.apps.StudentpageConfig',
    'TeacherPage.apps.TeacherpageConfig',
    'review.apps.ReviewConfig',
    "channels",
    "chat",

    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.naver",
    'aws_xray_sdk.ext.django'
]

SITE_ID = 2

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    "allauth.account.middleware.AccountMiddleware",
    'common.middleware.RoleRequiredMiddleware',
    'aws_xray_sdk.ext.django.middleware.XRayMiddleware',
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {  # 쓰기 전용 (200번)
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'academy_db',
        'USER': os.environ.get('DB_USER'),         
        'PASSWORD': os.environ.get('DB_PASSWORD'), 
        'HOST': os.environ.get('DB_MASTER_HOST'),
        'PORT': '3306',
    },
    'replica': {  # 읽기 전용 (201번)
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'academy_db',
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_SLAVE_HOST'),
        'PORT': '3306',
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
import os
from dotenv import load_dotenv

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

AUTH_USER_MODEL = 'common.CustomUser'

ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}
from django.contrib.messages import constants as messages_constants
# Message Storage Configuration - Uses session instead of cookies
# This prevents messages from being consumed by browser prefetch requests
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# 📧 이메일 전송 설정 (Gmail 기준)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tikitaka260225@gmail.com' # 👈 (수정) 발송용으로 쓸 구글 이메일 주소
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD') # 👈 (수정) 진짜 비밀번호 말고 '앱 비밀번호'
DEFAULT_FROM_EMAIL = f'TikiTaka 관리자 <{EMAIL_HOST_USER}>'

# -----------------------------------------
# ⏱️ 자동 로그아웃 (세션 타임아웃) 설정
# -----------------------------------------

# 1. 자동 로그아웃 될 시간 (초 단위)
# 예: 30분 = 30 * 60 = 1800초
SESSION_COOKIE_AGE = 43200 

# 2. (⭐ 가장 중요!) 유저가 활동(클릭, 새로고침 등)을 할 때마다 타이머 리셋하기
# 이 줄이 없으면 활동 여부와 상관없이 로그인 후 무조건 30분 뒤에 튕깁니다.
SESSION_SAVE_EVERY_REQUEST = True

# 3. (선택) 유저가 인터넷 브라우저 창(크롬 등)을 완전히 닫으면 즉시 로그아웃
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

AUTH_USER_MODEL = 'common.CustomUser'
SOCIALACCOUNT_ADAPTER = 'common.adapters.CustomSocialAccountAdapter'

SOCIALACCOUNT_LOGIN_ON_GET = True

DATABASE_ROUTERS = ['config.db_router.MasterSlaveRouter']

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

CSRF_TRUSTED_ORIGINS = [
    'https://whatmyname.click',
    'http://whatmyname.click',
    'https://www.whatmyname.click',
    'http://www.whatmyname.click',
]
# X-Ray 트레이싱 설정
XRAY_RECORDER = {
    'AWS_XRAY_TRACING_NAME': 'tikitaka-app',
    'PLUGINS': ('EC2Plugin',),
    'SAMPLING': True,
}
